### ISSUE TITLE
Multiple issues with the sample of createIssue

### ISSUE THREAD

**Issue by amitaibu** [haskell-github/github#194]
I'm still a newbie, so sorry if I'm getting those issues wrong:

While trying to follow the example of [CreateIssue.hs](https://github.com/phadej/github/blob/master/samples/Issues/CreateIssue.hs) the complier was complaining on several stuff. Not sure if the samples are not updated, or I got something else wrong, but it seems the imports have changed (I'll create a PR, if indeed it's a bug in the sample)

``` diff
- import qualified Github.Auth   as Github
- import qualified Github.Issues as Github
+ import qualified GitHub.Auth             as Github
+ import qualified GitHub.Data.Issues      as Github
+ import qualified GitHub.Endpoints.Issues as Github
```

Further more, it seems that `formatIssue` function is not updated:
- `Github.formatTime` doesn't seem to exist
- Some values return `Text` but it should be `unpack`ed.
- I wasn't able to get it to work completely (that newbie part again :wink: ) like how to deal with `(Github.simpleUserLogin $ Github.issueUser issue)`

After it did compile, I got a 422 error message due to "`properties/labels` being `nil`"

Here's the trimmed error:
`Error: HTTPError (StatusCodeException (Status {statusCode = 422, statusMessage = "Unprocessable Entity"}) [("X-Response-Body-Start","{\"message\":\"Invalid request.\\n\\nFor 'properties/labels', nil is not an array.\",\"documentation_url\":\"https://developer.github.com/v3/issues/#create-an-issue\"}")`

**Comment by phadej** [comment]
Unfortunately this is known issue, as you can see from https://github.com/phadej/github/issues/167

**Comment by amitaibu** [comment]
oh, sorry - I saw that issue, but wasn't sure it was related - the word `stack` confused me there ;)

If you would like I can create a PR for `CreateIssue.hs` as a first step to give me some real Haskell exercise. 
I'd appreciate some pointers on how/ where to fix the `(Github.simpleUserLogin $ Github.issueUser issue)` and the HTTPError, if possible :smile:

**Comment by phadej** [comment]
- `Github.formatTime` is dropped, we use `UTCTime` and functions on it
- Also we use `Text` all over the place, and it should be used in samples too
- I'm not sure what problem you have with `Github.simpleUserLogin $ Github.issueUser issue)`
- The HTTP error is due something serialised wrong, cannot say what exactly.

Please do PR, it doesn't need to be perfect right away. Every contribution is appreciated!

**Comment by amitaibu** [comment]
> I'm not sure what problem you have with `Github.simpleUserLogin $ Github.issueUser issue`

I couldn't (=didn't know how) to `unpack` it

> Please do PR

great, will do!
