### ISSUE TITLE
How to use IssueRepoMod ?

### ISSUE THREAD

**Issue by andreasabel** [haskell-github/github#286]
The example for `issuesForRepo` at https://hackage.haskell.org/package/github-0.16.0/docs/GitHub-Endpoints-Issues.html does not seem to work.
```haskell
issuesForRepo "thoughtbot" "paperclip" [NoMilestone, OnlyClosed, Mentions "jyurek", Ascending]
```
E.g. `OnlyClosed` is nowhere defined.
The documentation for `IssueRepoMod` at https://hackage.haskell.org/package/github-0.16.0/docs/GitHub-Data-Options.html#t:IssueRepoMod just says
```haskell
data IssueRepoMod
```
(no constructors exported).
There are a few smart constructors for `IssueRepoMod`, but all are boring, none lets me, for instance, filter by a milestone or issue status.

I tried to get help by looking at the supplied examples, e.g. https://github.com/phadej/github/blob/master/samples/Issues/IssueReport/Issues.hs
```haskell
...
import qualified Github.Issues as Github
...
main = do
  let limitations = [Github.OnlyClosed, Github.MilestoneId 4]
  possibleIssues <- Github.issuesForRepo' auth "paulrzcz" "hquantlib" limitations
...
```
None of this works.  For instance, neither `Github` nor `Github.Issues` exists as module.

??

**Comment by phadej** [comment]
The quick answer: look at `Has*` instances of `IssueRepoMod`, and it's `Monoid` so can be combined.

I don't know whether one can filter issues by milestone, probably via https://hackage.haskell.org/package/github-0.16.0/docs/GitHub-Endpoints-Search.html#v:searchIssuesR and  `milestone:"Checklist release" ` query (then you cannot sort&order, but that's small issue)

**Comment by andreasabel** [comment]
Thanks. 

> The quick answer: look at Has* instances of IssueRepoMod, also it's a Monoid so can be combined.

I think the explanations should go into the haddockumentation.

> probably via https://hackage.haskell.org/package/github-0.16.0/docs/GitHub-Endpoints-Search.html#v:searchIssuesR 

That does not look right; also, I would like the structured queries rather than composing some query string manually.

**Comment by phadej** [comment]
@andreasabel the structured query vs. composing query string is a problem in the space of `postgresql-simple` vs. `opaleye`. With the difference that GitHub doesn't really document about the "query language" :(

However, I'm not against having some structured search query string *in addition* to untyped escape hatch. Could you list what predicates you definitely need, or example queries (I guess you want something like https://github.com/agda/agda/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.6.0)?

Documentaton PRs are always very welcomed.

**Comment by andreasabel** [comment]
I put at #288 what I want to do: get all closed issues for a milestone.
From reading the source of the `github` package, I got the feeling that filtering for a milestone is provided for, but somehow not available. (See my question at #287.)

Look at this part of `GitHub.Data.Options`:
```haskell
toIssueRepoOptions :: IssueRepoMod -> IssueRepoOptions
toIssueRepoOptions (IssueRepoMod f) = f defaultIssueRepoOptions

issueRepoModToQueryString :: IssueRepoMod -> QueryString
issueRepoModToQueryString = issueRepoOptionsToQueryString . toIssueRepoOptions

issueRepoOptionsToQueryString :: IssueRepoOptions -> QueryString
issueRepoOptionsToQueryString IssueRepoOptions {..} =
    [ mk "state"     state'
    , mk "sort"      sort'
    , mk "direction" direction'
    ] ++ catMaybes
    [ mk "milestone" <$> milestone'
    , mk "assignee"  <$> assignee'
    , mk "labels"    <$> labels'
    , mk "since"     <$> since'
    , mk "creator"   <$> creator'
    , mk "mentioned" <$> mentioned'
    ]
  where
    mk k v = (k, Just v)
    filt f x = case x of
        FilterAny          -> Just "*"
        FilterNone         -> Just "none"
        FilterBy x'        -> Just $ TE.encodeUtf8 $ f x'
        FilterNotSpecified -> Nothing

    milestone' = filt (T.pack . show . untagId) issueRepoOptionsMilestone
...
```
This provides a translation from `IssueRepoMod` to `QueryString`, including milestone filtering: the content of `issueRepoOptionsMilestone` can be a `FilterBy` with a milestone id.
However, I could not find a way to access this functionality.
I found not a single piece of code in the `github` package that __constructs__ a `FilterBy` value.  And `FilterBy` is not exported.

How can I make use of this functionality?

**Comment by phadej** [comment]
It can be so that I just forgot to export things. I'll check what's going on.

**Comment by develop7** [comment]
I've just figured the `stateAll <> sortDescending <> sortByUpdated` concept on my own (thanks to `mempty` in the samples), but the examples (under the samples directory) drove me way off. Could they be deleted altogether?
