### ISSUE TITLE
Add support for GitHub Actions

### ISSUE THREAD

**Issue by K0Te** [haskell-github/github#458]
Hi,

Actions API: https://docs.github.com/en/rest/reference/actions
I am using this library for pull requests and comments, but now I also need to trigger workflows using "workflow dispatch event".

Should actions API be added to this library?
If so, can I help with implementation? Looks like no PRs have been merged lately, so I'm asking for guidance before sending any PRs.

**Comment by phadej** [comment]
No PR was merged recently as there weren't no merge-worthy PR!

Interestingly, actions artifacts are **not** a preview feature in the API, which is good news.
