### ISSUE TITLE
searchIssuesR leads to an error from GitHub when searching by multiple conditions

### ISSUE THREAD

**Issue by pavelkucera** [haskell-github/github#482]
Hi,

I was wondering if you could help me figure out an issue where calling `searchIssuesR` fails when I try to search by multiple conditions (repository / state of a PR). From the outside it looks like there is an issue in how `q` gets encoded when passed to GitHub, but I am guessing here.

## Fails: searching for open PRs in a public repository

I am trying to replicate request such as:
```bash
curl "https://api.github.com/search/issues?q=is:pr+repo:haskell-github/github+is:pr+state:open"
```
which succeeds (modulo rate limiting)

With code:
```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import qualified GitHub as GH

main = do
  result <- GH.github' (GH.searchIssuesR "repo:haskell-github/github+is:pr+state:open" (GH.FetchAtLeast 1))
  print result
```
which fails with a 422 response from GitHub:
```json
{"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://docs.github.com/v3/search/"}
```

## Succeeds: searching for all issues in a public repository

Interestingly, searching for all issues in a public repository succeeds.

Curl:
```bash
curl "https://api.github.com/search/issues?q=is:pr+repo:haskell-github/github"
```

Code:
```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import qualified GitHub as GH

main = do
  result <- GH.github' (GH.searchIssuesR "repo:haskell-github/github" (GH.FetchAtLeast 1))
  print result
```
This prints issues/PRs of the repository.

## How to debug this further?

Since searching just by repository works, but it stops working when I add more conditions, it leads me to believe that `q` doesn't get encoded properly., but it is only a guess. And I'm not quite sure how to debug this further. Would you have any advice?

Using `v0.28` of GitHub, and GHC `8.10.7`.

Thanks for any help!

**Comment by modotte** [comment]
@pavelkucera Hello!

I think replacing `+` with plain space should fix the issue in your case as shown [here](https://github.com/haskell-github/github/blob/299ad10ea23d9df5819f5e64dec9dd664ba74bb7/spec/GitHub/SearchSpec.hs#L57) (and it did fix it in my local testing session)

**Comment by pavelkucera** [comment]
@modotte Thank you! You're right, using a space works.
